### ISSUE TITLE
Some ppl (me) need a section indicating how to properly install the gem

### ISSUE THREAD

**Issue by TheNotary** [omghax/jruby-sandbox#8]
Hey, first off great work on this gem if i'm understanding the readme correctly.  This is exactly what I need to setup a cool flashcard style ruby and rails mental refresher app.  It will be fun and have colors!

Ok, so I followed the compile process, and that zany .jar file sure enough showed up in the lib directory, but then I had to really stretch my ruby thought muscles and run the command `rake install` to install the gem.  But it would turn out that... that doesn't even work because when I try to require in sandbox, ruby returns with a load error in irb.  

Edit:

I was forgetting to require 'rubygems'.

**Comment by nilbus** [comment]
I think this can be closed. `gem install jruby_sandbox` is pretty straightforward.

**Comment by TheNotary** [comment]
I don't see that in the readme so that would probably be good to add, especially considering the gem name on rubygems.org differes from the name of the repo project.  

But also the building procedures are still incomplete and should be looked at for anyone who's installing from github and developing features or maintaining the code which was what this issue originally referred to.  

This project doesn't seem to be maintained anymore, but I just attempted a rake compile and I'm getting a new error message on that now:

```
jruby-sandbox $ bundle
Fetching git://github.com/nanothief/fakefs.git
fatal: remote error: 
  Repository not found.
Git error: command `git clone 'git://github.com/nanothief/fakefs.git'
"/home/kentos/.rvm/gems/jruby-1.6.3@jruby_sandbox/cache/bundler/git/fakefs-f16205ea5923812eaccac13c927ba6813a952fb7"
--bare --no-hardlinks` in directory /home/kentos/dev/ruby/sc/new/jruby-sandbox
has failed.

jruby-sandbox $ rake compile
rake aborted!
no such file to load -- rake/javaextensiontask
org/jruby/RubyKernel.java:1038:in `require'
/home/kentos/dev/ruby/sc/new/jruby-sandbox/Rakefile:4:in `(root)'
org/jruby/RubyKernel.java:1063:in `load'
/home/kentos/dev/ruby/sc/new/jruby-sandbox/Rakefile:25:in `load_rakefile'
/home/kentos/.rvm/gems/jruby-1.6.3@global/gems/rake-10.0.4/lib/rake/application.rb:589:in `raw_load_rakefile'
/home/kentos/.rvm/gems/jruby-1.6.3@global/gems/rake-10.0.4/lib/rake/application.rb:89:in `load_rakefile'
/home/kentos/.rvm/gems/jruby-1.6.3@global/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/home/kentos/.rvm/gems/jruby-1.6.3@global/gems/rake-10.0.4/lib/rake/application.rb:88:in `load_rakefile'
/home/kentos/.rvm/gems/jruby-1.6.3@global/gems/rake-10.0.4/lib/rake/application.rb:72:in `run'
/home/kentos/.rvm/gems/jruby-1.6.3@global/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/home/kentos/.rvm/gems/jruby-1.6.3@global/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
org/jruby/RubyKernel.java:1063:in `load'
org/jruby/RubyKernel.java:1088:in `eval'
/home/kentos/.rvm/gems/jruby-1.6.3@global/bin/ruby_noexec_wrapper:14:in `(root)'
(See full trace by running task with --trace)
```

Something worth looking into if anyone is interested in taking up this project again.

**Comment by nilbus** [comment]
I'm doing a little work on this gem and got that working. I'll submit
a PR soon including updates to the readme. If you want to build before
then, just alter the Gemfile to use the normal fakefs gem from
rubygems instead of the one from GitHub that no longer exists. It
supports 1.9 now, so it should do fine.
